beans:
  - beanName: splitterBean
    className: org.example.SplitterBean
    constructorArgs:
      divider: "-"
    dependsOn:
      - uppercaseBean
  - beanName: uppercaseBean
    className: org.example.UppercaseBean
    constructorArgs:
      suffix: " PROCESSED"
  - beanName: suffixBean
    className: org.example.SuffixBean
    constructorArgs:
      suffix: " APPENDED"
